name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main
      - 'feature/**'

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            npm run build -- --configuration production --base-href "/nhl-chem/"
          else
            npm run build -- --configuration production --base-href "/nhl-chem/${GITHUB_REF_NAME}/"
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/nhl-chem/browser
          destination_dir: ${{ github.ref_name }}
